"Resource/UI/HudPlayerHealth.res"
{   
    // player health data
    "HudPlayerHealth"
    {
        "ControlName"   "EditablePanel"
        "fieldName"     "HudPlayerHealth"
        "ypos"          "200"   [$WIN32]
        "xpos"          "c-425"     [$WIN32]
        "zpos"          "2"
        "wide"          "460"
        "tall"          "280"
        "visible"       "1"
        "enabled"       "1" 
        "HealthBonusPosAdj" "35"
        "HealthDeathWarning"    "0.49"
        "HealthDeathWarningColor"   "HUDDeathWarning"
    }
    "HudPlayerHealthBoxBG"
    {
        "ControlName"   "CTFImagePanel"
        "fieldName"     "HudPlayerHealthBoxBG"
        "font"          "ItemFontNameSmallest"
        "labelText"     ""
        "textAlignment" "north-west"
        "xpos"          "235"
        "ypos"          "150"
        "zpos"          "-1"
        "wide"          "90"
        "wide_minmode"  "80"
        "tall_minmode"  "30"
        "tall"          "40"
        "visible"       "1"
        "image"         "../hud/color_panel_brown"
        "scaleImage"        "1"
        "teambg_1"      "../hud/color_panel_brown"
        "teambg_2"      "../hud/color_panel_red"
        "teambg_2_lodef"    "../hud/color_panel_red"
        "teambg_3"      "../hud/color_panel_blu"
        "teambg_3_lodef"    "../hud/color_panel_blu"
    
        "src_corner_height"     "23"                // pixels inside the image
        "src_corner_width"      "23"
        
        "draw_corner_width"     "5"             // screen size of the corners ( and sides ), proportional
        "draw_corner_height"    "5"     
    }   
    "PlayerStatusHealthImage"
    {
        "ControlName"   "ImagePanel"
        "fieldName"     "PlayerStatusHealthImage"
        "ypos"          "0"
        "zpos"          "4"
        "wide"          "0"
        "tall"          "0"
        "visible"       "1"
        "enabled"       "1"
        "scaleImage"    "1" 
        "xpos"          "255"
        "alpha"         "0"
    }       
    "PlayerStatusHealthImageBG"
    {
        "ControlName"   "ImagePanel"
        "fieldName"     "PlayerStatusHealthImageBG"
        "xpos"          "9999"
        "ypos"          "9999"
        "zpos"          "3"
        "visible"       "1"
        "enabled"       "1"
        "image"         "../hud/health_bg"
        "scaleImage"    "1" 
    }   
    "PlayerStatusHealthBonusImage"
    {
        "ControlName"   "ImagePanel"
        "fieldName"     "PlayerStatusHealthBonusImage"
        "xpos"          "9999"   // "9999" to disable health cross
        "ypos"          "9999"   // "9999" to disable health cross
        "xpos_minmode"  "9999"   // "9999" to disable health cross
        "ypos_minmode"  "9999"   // "9999" to disable health cross
        "zpos"          "2"
        "wide"          "60"
        "tall"          "60"
        "wide_minmode"  "30"
        "tall_minmode"  "30"
        "visible"       "1"
        "enabled"       "1"
        "image"         "../hud/health_over_bg"
        "scaleImage"    "1" 
    }
    "PlayerStatusHealthBig"
    {
        "ControlName"   "CExLabel"
        "fieldName"     "PlayerStatusHealthBig"
        "xpos"          "205"
        "ypos"          "145"
        "xpos_minmode"  "200"
        "ypos_minmode"  "140"
        "zpos"          "5"
        "wide"          "150"
        "tall"          "50"
        "visible"       "1"
        "enabled"       "1"
        "labelText"     "%Health%"
        "textAlignment" "center"
        "font"          "HudFontGiantBold"
        "font_minmode"  "HudFontMediumBigBold"
        "fgcolor"       "TanLight"
    }   
    "PlayerStatusHealthBigShadow"
    {
        "ControlName"   "CExLabel"
        "fieldName"     "PlayerStatusHealthBigShadow"
        "xpos"          "206"
        "ypos"          "146"
        "xpos_minmode"  "201"
        "ypos_minmode"  "141"
        "zpos"          "4"
        "wide"          "150"
        "tall"          "50"
        "visible"       "1"
        "enabled"       "1"
        "labelText"     "%Health%"
        "textAlignment" "center"    
        "font"          "HudFontGiantBold"
        "font_minmode"  "HudFontMediumBigBold"
        "fgcolor"       "Black"
    }   
    "PlayerStatusBleedImage"
    {
        "ControlName"   "ImagePanel"
        "fieldName"     "PlayerStatusBleedImage"
        "xpos"          "50"
        "ypos"          "90"
        "zpos"          "7"
        "wide"          "32"
        "tall"          "32"
        "visible"       "1"
        "enabled"       "1"
        "scaleImage"    "1" 
        "image"         "../vgui/bleed_drop"
        "fgcolor"       "TanDark"
        
        //"xpos_minmode"  "34"
        //"ypos_minmode"  "60"
        //"wide_minmode"  "24"
        //"tall_minmode"  "24"
    }       
    "PlayerStatusMilkImage"
    {
        "ControlName"   "ImagePanel"
        "fieldName"     "PlayerStatusMilkImage"
        "xpos"          "50"
        "ypos"          "90"
        "zpos"          "7"
        "wide"          "32"
        "tall"          "32"
        "visible"       "1"
        "enabled"       "1"
        "scaleImage"    "1" 
        "image"         "../vgui/bleed_drop"
        "fgcolor"       "TanDark"
        
        //"xpos_minmode"  "34"
        //"ypos_minmode"  "60"
        //"wide_minmode"  "24"
        //"tall_minmode"  "24"
    }
    "PlayerStatusMarkedForDeathImage"
    {
        "ControlName"   "ImagePanel"
        "fieldName"     "PlayerStatusMarkedForDeathImage"
        "xpos"          "50"
        "ypos"          "90"
        "zpos"          "7"
        "wide"          "32"
        "tall"          "32"
        "visible"       "1"
        "enabled"       "1"
        "scaleImage"    "1" 
        "image"         "../vgui/marked_for_death"
        "fgcolor"       "TanDark"
        
        //"xpos_minmode"  "34"
        //"ypos_minmode"  "60"
        //"wide_minmode"  "24"
        //"tall_minmode"  "24"
    }
    "PlayerStatusMarkedForDeathSilentImage"
    {
        "ControlName"   "ImagePanel"
        "fieldName"     "PlayerStatusMarkedForDeathSilentImage"
        "xpos"          "50"
        "ypos"          "90"
        "zpos"          "7"
        "wide"          "31"
        "tall"          "31"
        "visible"       "1"
        "enabled"       "1"
        "scaleImage"    "1" 
        "image"         "../vgui/marked_for_death"
        "fgcolor"       "TanDark"
        
        //"xpos_minmode"  "34"
        //"ypos_minmode"  "60"
        //"wide_minmode"  "23"
        //"tall_minmode"  "23"
    }
    "PlayerStatus_MedicUberBulletResistImage"
    {
        "ControlName"   "ImagePanel"
        "fieldName"     "PlayerStatus_MedicUberBulletResistImage"
        "xpos"          "50"
        "ypos"          "90"
        "zpos"          "7"
        "wide"          "31"
        "tall"          "31"
        "visible"       "1"
        "enabled"       "1"
        "scaleImage"    "1" 
        "image"         "../HUD/defense_buff_bullet_blue"
        "fgcolor"       "TanDark"
        
        //"xpos_minmode"  "34"
        //"ypos_minmode"  "60"
        //"wide_minmode"  "23"
        //"tall_minmode"  "23"
    }
    "PlayerStatus_MedicUberBlastResistImage"
    {
        "ControlName"   "ImagePanel"
        "fieldName"     "PlayerStatus_MedicUberBlastResistImage"
        "xpos"          "50"
        "ypos"          "90"
        "zpos"          "7"
        "wide"          "31"
        "tall"          "31"
        "visible"       "1"
        "enabled"       "1"
        "scaleImage"    "1" 
        "image"         "../HUD/defense_buff_explosion_blue"
        "fgcolor"       "TanDark"
        
        //"xpos_minmode"  "34"
        //"ypos_minmode"  "60"
        //"wide_minmode"  "23"
        //"tall_minmode"  "23"
    }
    "PlayerStatus_MedicUberFireResistImage"
    {
        "ControlName"   "ImagePanel"
        "fieldName"     "PlayerStatus_MedicUberFireResistImage"
        "xpos"          "50"
        "ypos"          "90"
        "zpos"          "7"
        "wide"          "31"
        "tall"          "31"
        "visible"       "1"
        "enabled"       "1"
        "scaleImage"    "1" 
        "image"         "../HUD/defense_buff_fire_blue"
        "fgcolor"       "TanDark"
        
        //"xpos_minmode"  "34"
        //"ypos_minmode"  "60"
        //"wide_minmode"  "23"
        //"tall_minmode"  "23"
    }

    "PlayerStatus_MedicSmallBulletResistImage"
    {
        "ControlName"   "ImagePanel"
        "fieldName"     "PlayerStatus_MedicSmallBulletResistImage"
        "xpos"          "50"
        "ypos"          "90"
        "zpos"          "7"
        "wide"          "31"
        "tall"          "31"
        "visible"       "1"
        "enabled"       "1"
        "scaleImage"    "1" 
        "image"         "../HUD/defense_buff_bullet_blue"
        "fgcolor"       "TanDark"
        
        //"xpos_minmode"  "34"
        //"ypos_minmode"  "60"
        //"wide_minmode"  "23"
        //"tall_minmode"  "23"
    }
    "PlayerStatus_MedicSmallBlastResistImage"
    {
        "ControlName"   "ImagePanel"
        "fieldName"     "PlayerStatus_MedicSmallBlastResistImage"
        "xpos"          "50"
        "ypos"          "90"
        "zpos"          "7"
        "wide"          "31"
        "tall"          "31"
        "visible"       "1"
        "enabled"       "1"
        "scaleImage"    "1" 
        "image"         "../HUD/defense_buff_explosion_blue"
        "fgcolor"       "TanDark"
        
        //"xpos_minmode"  "34"
        //"ypos_minmode"  "60"
        //"wide_minmode"  "23"
        //"tall_minmode"  "23"
    }
    "PlayerStatus_MedicSmallFireResistImage"
    {
        "ControlName"   "ImagePanel"
        "fieldName"     "PlayerStatus_MedicSmallFireResistImage"
        "xpos"          "50"
        "ypos"          "90"
        "zpos"          "7"
        "wide"          "31"
        "tall"          "31"
        "visible"       "1"
        "enabled"       "1"
        "scaleImage"    "1" 
        "image"         "../HUD/defense_buff_fire_blue"
        "fgcolor"       "TanDark"
        
        //"xpos_minmode"  "34"
        //"ypos_minmode"  "60"
        //"wide_minmode"  "23"
        //"tall_minmode"  "23"
    }
    

    "PlayerStatus_WheelOfDoom"
    {
        "ControlName"   "ImagePanel"
        "fieldName"     "PlayerStatus_WheelOfDoom"
        "xpos"          "50"
        "ypos"          "90"
        "zpos"          "7"
        "wide"          "32"
        "tall"          "32"
        "visible"       "1"
        "enabled"       "1"
        "scaleImage"    "1" 
        "image"         "../signs/death_wheel_whammy"
        "fgcolor"       "TanDark"
        
        //"xpos_minmode"  "34"
        //"ypos_minmode"  "60"
        //"wide_minmode"  "24"
        //"tall_minmode"  "24"
    }

    "PlayerStatus_SoldierOffenseBuff"
    {
        "ControlName"   "ImagePanel"
        "fieldName"     "PlayerStatus_SoldierOffenseBuff"
        "xpos"          "50"
        "ypos"          "90"
        "zpos"          "7"
        "wide"          "31"
        "tall"          "31"
        "visible"       "1"
        "enabled"       "1"
        "scaleImage"    "1" 
        "image"         "../HUD/defense_buff_bullet_blue"
        "fgcolor"       "TanDark"
        
        //"xpos_minmode"  "34"
        //"ypos_minmode"  "60"
        //"wide_minmode"  "23"
        //"tall_minmode"  "23"
    }

    "PlayerStatus_SoldierDefenseBuff"
    {
        "ControlName"   "ImagePanel"
        "fieldName"     "PlayerStatus_SoldierDefenseBuff"
        "xpos"          "50"
        "ypos"          "90"
        "zpos"          "7"
        "wide"          "31"
        "tall"          "31"
        "visible"       "1"
        "enabled"       "1"
        "scaleImage"    "1" 
        "image"         "../HUD/defense_buff_bullet_blue"
        "fgcolor"       "TanDark"
        
        //"xpos_minmode"  "34"
        //"ypos_minmode"  "60"
        //"wide_minmode"  "23"
        //"tall_minmode"  "23"
    }

    "PlayerStatus_SoldierHealOnHitBuff"
    {
        "ControlName"   "ImagePanel"
        "fieldName"     "PlayerStatus_SoldierHealOnHitBuff"
        "xpos"          "50"
        "ypos"          "90"
        "zpos"          "7"
        "wide"          "31"
        "tall"          "31"
        "visible"       "1"
        "enabled"       "1"
        "scaleImage"    "1" 
        "image"         "../HUD/defense_buff_bullet_blue"
        "fgcolor"       "TanDark"
        
        //"xpos_minmode"  "34"
        //"ypos_minmode"  "60"
        //"wide_minmode"  "23"
        //"tall_minmode"  "23"
    }
}
